package com.csye6225.spring2019.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "announcement")
public class Announcement {
	private String announcementId;
	private String boardId;
	private String announcementText;
	private static final int MAX_LEN = 160;

	public Announcement() {
	}

	public Announcement(String announcementId, String boardId, String announcementText) {
		super();
		this.announcementId = announcementId;
		this.boardId = boardId;
		if(announcementText.length() > MAX_LEN) {
			announcementText = announcementText.substring(0, MAX_LEN);
		}
		
		this.announcementText = announcementText;
	}
	
	@DynamoDBHashKey(attributeName = "announcementId")
	@DynamoDBAutoGeneratedKey
	public String getAnnouncementId() {
		return announcementId;
	}

	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}

	@DynamoDBIndexHashKey(attributeName = "boardId", globalSecondaryIndexName="boardId_Index")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName = "announcementText")
	public String getAnnouncementText() {
		return announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		if(announcementText.length() > MAX_LEN) {
			announcementText = announcementText.substring(0, MAX_LEN);
		}
		
		this.announcementText = announcementText;
	}
	
	@DynamoDBIgnore
	@Override
	public String toString() {
		return "Announcement [announcementId=" + announcementId + ", boardId=" + boardId
				+ ", announcementText=" + announcementText + "]";
	}
}
