package com.csye6225.spring2019.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "board")
public class Board {
	private String boardId;
	private String courseId;

	public Board() {
	}

	public Board(String boardId, String courseId) {
		super();
		this.boardId = boardId;
		this.courseId = courseId;
	}

	@DynamoDBHashKey(attributeName = "boardId")
	@DynamoDBAutoGeneratedKey
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "courseId_Index")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "Board [boardId=" + boardId + ", courseId=" + courseId + "]";
	}
}
