package com.csye6225.spring2019.courseservice.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "course")
public class Course {
	private String courseName;
	private String courseId;
	private String professorId;
	private String taId;
	private String boardId;
	private String department;
	private List<String> roster;

	public Course() {

	}

	public Course(String courseName, String courseId, String professorId, String taId, String boardId,
			String department, List<String> roster) {
		super();
		this.courseName = courseName;
		this.courseId = courseId;
		this.professorId = professorId;
		this.taId = taId;
		this.boardId = boardId;
		this.department = department;
		this.roster = roster;
	}

	@DynamoDBHashKey(attributeName = "courseId")
	@DynamoDBAutoGeneratedKey
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	
	@DynamoDBIndexHashKey(attributeName = "professorId", globalSecondaryIndexName = "professorId_Index")
	public String getProfessorId() {
		return professorId;
	}

	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName = "courseName")
	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@DynamoDBAttribute(attributeName = "taId")
	public String getTaId() {
		return taId;
	}

	public void setTaId(String taId) {
		this.taId = taId;
	}

	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "roster")
	public List<String> getRoster() {
		return roster;
	}

	public void setRoster(List<String> roster) {
		this.roster = roster;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "Course [courseName=" + courseName + ", courseId=" + courseId + ", professorId="
				+ professorId + ", taId=" + taId + ", boardId=" + boardId + ", department=" + department + ", roster="
				+ roster + "]";
	}
}
